name: SonarQube on Local Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted # Use your self-hosted runner, installed locally
    
    steps:
      - name: Add SonarQube Helm repository
        run: |
          helm repo add sonarqube https://sonarsource.github.io/helm-chart-sonarqube
          helm repo update
      
      - name: Create sonarqube namespace if it does not exist
        # Check if the namespace exists and only create it if it doesn't.
        run: |
          $namespace = "sonarqube"
          if (-not (kubectl get namespace $namespace -ErrorAction SilentlyContinue)) {
            kubectl create namespace $namespace
          }
        shell: powershell # Specify powershell for PowerShell Core syntax
      
      - name: Install SonarQube with Helm
        run: |
          helm upgrade --install sonarqube sonarqube/sonarqube `
            --namespace sonarqube `
            --set monitoringPasscode=your_secure_passcode `
            --set community.enabled=true
        env:
          MONITORING_PASSCODE: 'your_secure_passcode' # Replace with a secure password
        shell: powershell
        
      - name: Wait for SonarQube pods to be ready
        run: |
          kubectl wait --namespace=sonarqube `
            --for=condition=ready pod `
            --selector=app.kubernetes.io/name=sonarqube `
            --timeout=600s
        shell: powershell
        
      - name: Get SonarQube service URL
        id: expose-sonarqube
        run: |
          $sonarqubeUrl = minikube service sonarqube --namespace sonarqube --url
          echo "SONARQUBE_URL=$sonarqubeUrl" >> $env:GITHUB_OUTPUT
        shell: powershell
        
      - name: Display SonarQube access information
        run: |
          Write-Host "SonarQube is now running and accessible at:"
          Write-Host "URL: ${{ steps.expose-sonarqube.outputs.SONARQUBE_URL }}"
          Write-Host "Username: admin"
          Write-Host "Password: admin"
          Write-Host "Please change the default password after your first login."
        shell: powershell

      - name: Test access to SonarQube
        run: |
          curl -s --head "${{ steps.expose-sonarqube.outputs.SONARQUBE_URL }}"
        shell: powershell

        
